apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
  namespace: fleetman
spec:
  clusterIP: None
  selector:
    app: fleetman-mongodb
  ports:
    - port: 27017
      targetPort: 27017
