apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
  namespace: fleetman
spec:
  selector:
    app: fleetman-position-simulator
  ports:
    - port: 8080
      targetPort: 8080
