apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  namespace: fleetman
spec:
  selector:
    app: fleetman-queue
  ports:
    - port: 8161
      targetPort: 8161
      name: management
    - port: 61616
      targetPort: 61616
      name: messaging
