apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  namespace: fleetman
spec:
  selector:
    app: fleetman-webapp
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
  nodePort: 30080
